version: '3.5'

services:
  backend:
    build: .
    image: backend:latest
    networks:
      - backend
    command: npm run start:dev
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/backend
      - /usr/src/backend/node_modules
    ports:
      - 3000:3000

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5431:5433
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=miniature-game-db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6378:6379

networks:
  backend:
    driver: overlay
    driver_opts:
      encrypted: 'true'
